[profile.default]
libs = ['lib']
test = 'test'

# Require read access for 'addresses' and 'out' folder on root repo for bytecode verification
fs_permissions = [{ access = "read", path = "../../"}]
evm_version = 'paris'
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
sepolia = "https://sepolia.drpc.org"


